version: "3"

services:
    doc:
        build: docker/doc
        volumes:
            - ./docs:/etc/Sphinx/source
        ports:
            - 8100:80
    auto_changelog:
        build: docker/auto-changelog
        working_dir: /src
        volumes:
            - .:/src
    app:
        build:
            context: .
            dockerfile: docker/php-fpm/debian/Dockerfile
        volumes:
            - .:/var/www
        platform: linux/amd64
